### ISSUE TITLE
Verify production problem

### ISSUE THREAD

**Issue by vindevoy** [vindevoy/cherryblog#161]
2020-04-24 21:16:24,327 [WARNING] COMMON.CONTENT COULD NOT FIND THE YAML FILE posts/0006_version_1_0_0.md
2020-04-24 21:16:24,329 [ERROR] [24/Apr/2020:21:16:24] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/local/lib64/python3.6/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/usr/local/lib64/python3.6/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/cherryblog.org/src/application/controller/application.py", line 86, in posts
    data = DataLoader().posts_data(post)
  File "/opt/cherryblog.org/src/application/controller/data_loader.py", line 170, in posts_data
    data, _, _ = Posts().data(post)  # We don't do anything with the meta and raw data yet
  File "/opt/cherryblog.org/src/application/model/posts.py", line 56, in data
    meta, content, html = Content().read_content(self.__base_dir, '{0}.md'.format(post))
ValueError: not enough values to unpack (expected 3, got 2)
2020-04-24 21:16:24,340 [INFO] [24/Apr/2020:21:16:24] HTTP 
Request Headers:
  Remote-Addr: 66.249.79.60
  HOST: www.cherryblog.org
  AMP-CACHE-TRANSFORM: google;v="1..3"
  CONNECTION: keep-alive
  ACCEPT: text/html,application/xhtml+xml,application/signed-exchange;v=b3,application/xml;q=0.9,*/*;q=0.8
  FROM: googlebot(at)googlebot.com
  USER-AGENT: Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
  ACCEPT-ENCODING: gzip,deflate,br
  IF-MODIFIED-SINCE: Wed, 08 Apr 2020 06:47:28 GMT

**Comment by vindevoy** [comment]
Can be closed.  This problem happens when the data is renewed with a git pull but the application is not restarted.  

Problem is known and already ticketed.  The ticket with the data reload when data changes will solve this.  For now, when data is removed/changed, you must restart the application quickly.
